ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT9XXTB_hotknot/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT9XXTB_hotknot/include/firmware_default/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT9XXTB_hotknot/include/config_default/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y	+=  gt9xx_driver.o
obj-y	+=  goodix_tool.o
obj-y	+=  gt9xx_update.o
#obj-y	+=  gt9xx_openshort.o

