/*
 * Copyright (C) 2015 MediaTek Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

//s_add new sensor driver here
//export funtions
/* IMX */
UINT32 IMX219_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 IMX145_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 IMX179_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 IMX237_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 IMX190_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 IMX149_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 IMX258_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
/* S5K */
UINT32 S5K3H7_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
/* GC */
UINT32 GC5025_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC2755_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC2755_1LANE_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC2355_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC2365MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC2375MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC5005MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC5005MIPI_SUB_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC8024MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC2385MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC2155MIPI_YUV_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC8034MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC0310_YUV_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);

/* SP */
UINT32 SP2509MIPISensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 SP250A_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 SP2609MIPISensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 SP8407_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 SP5506MIPISensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 SP5506_SUB_MIPISensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 SP5407_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 SP5509MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
/* MN */
UINT32 MN34172_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 MN045MIPISensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
/* IMX */
UINT32 IMX219_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 IMX135_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 IMX214_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
/* OV */
UINT32 OV9760_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV8865_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV13850_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV5675_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV5648MIPISensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV8858_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV8856_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV5693_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV5670_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
/* HM */
UINT32 HM8040_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 HM5040_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
/*bf*/
UINT32 BF2206MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);

/*VD*/
UINT32 VD6955MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);


/* S5K */
UINT32 S5K3L2_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 S5K3M2_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 S5K3L8_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 S5K4H8_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 S5K3H7YX_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 S5K3H2_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 S5K3H2_MIPI_RAW_CXT_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);

/*HI*/
UINT32 HI545_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 HI351_YUV_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);

/*AR*/
UINT32 AR0543_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);

//! Add Sensor Init function here
//! Note:
//! 1. Add by the resolution from ""large to small"", due to large sensor
//!    will be possible to be main sensor.
//!    This can avoid I2C error during searching sensor.
//! 2. This file should be the same as mediatek\custom\common\hal\imgsensor\src\sensorlist.cpp
ACDK_KD_SENSOR_INIT_FUNCTION_STRUCT kdSensorList[MAX_NUM_OF_SUPPORT_SENSOR+1] =
{
/*bf*/
#if defined(BF2206_MIPI_RAW)
    {BF2206MIPI_SENSOR_ID,SENSOR_DRVNAME_BF2206MIPI_RAW,BF2206MIPI_RAW_SensorInit},
#endif
/* OV */
#if defined(OV9760_MIPI_RAW)
    {OV9760_SENSOR_ID, SENSOR_DRVNAME_OV9760_MIPI_RAW,OV9760_MIPI_RAW_SensorInit},
#endif
#if defined(OV8865_MIPI_RAW)
    {OV8865_SENSOR_ID, SENSOR_DRVNAME_OV8865_MIPI_RAW,OV8865_MIPI_RAW_SensorInit},
#endif
#if defined(OV13850_MIPI_RAW)
    {OV13850_SENSOR_ID, SENSOR_DRVNAME_OV13850_MIPI_RAW,OV13850_MIPI_RAW_SensorInit},
#endif
#if defined(OV5675_MIPI_RAW)
    {OV5675MIPI_SENSOR_ID, SENSOR_DRVNAME_OV5675_MIPI_RAW, OV5675_MIPI_RAW_SensorInit},
#endif
#if defined(OV5648_MIPI_RAW)
    {OV5648MIPI_SENSOR_ID, SENSOR_DRVNAME_OV5648_MIPI_RAW, OV5648MIPISensorInit},
#endif
#if defined(OV8858_MIPI_RAW)
    {OV8858_SENSOR_ID, SENSOR_DRVNAME_OV8858_MIPI_RAW, OV8858_MIPI_RAW_SensorInit},
#endif
#if defined(OV8856_MIPI_RAW)
    {OV8856_SENSOR_ID, SENSOR_DRVNAME_OV8856_MIPI_RAW, OV8856_MIPI_RAW_SensorInit},
#endif
#if defined(OV5693_MIPI_RAW)
    {OV5693_SENSOR_ID, SENSOR_DRVNAME_OV5693_MIPI_RAW, OV5693_MIPI_RAW_SensorInit},
#endif
#if defined(OV5670_MIPI_RAW)
    {OV5670MIPI_SENSOR_ID, SENSOR_DRVNAME_OV5670_MIPI_RAW, OV5670_MIPI_RAW_SensorInit},
#endif
/* HM */
#if defined(HM8040_MIPI_RAW)
    {HM8040_SENSOR_ID, SENSOR_DRVNAME_HM8040_MIPI_RAW,HM8040_MIPI_RAW_SensorInit},
#endif
#if defined(HM5040_MIPI_RAW)
    {HM5040_SENSOR_ID, SENSOR_DRVNAME_HM5040_MIPI_RAW,HM5040_MIPI_RAW_SensorInit},
#endif

/*VD*/
#if defined(VD6955_MIPI_RAW)
    {VD6955MIPI_SENSOR_ID, SENSOR_DRVNAME_VD6955_MIPI_RAW,VD6955MIPI_RAW_SensorInit},
#endif
/* IMX */
#if defined(IMX219_MIPI_RAW)
    {IMX219_SENSOR_ID, SENSOR_DRVNAME_IMX219_MIPI_RAW, IMX219_MIPI_RAW_SensorInit},
#endif
#if defined(IMX145_MIPI_RAW)
    {IMX145_SENSOR_ID, SENSOR_DRVNAME_IMX145_MIPI_RAW, IMX145_MIPI_RAW_SensorInit},
#endif
#if defined(IMX179_MIPI_RAW)
    {IMX179_SENSOR_ID, SENSOR_DRVNAME_IMX179_MIPI_RAW, IMX179_MIPI_RAW_SensorInit},
#endif
#if defined(IMX135_MIPI_RAW)
    {IMX135_SENSOR_ID, SENSOR_DRVNAME_IMX135_MIPI_RAW, IMX135_MIPI_RAW_SensorInit},
#endif
#if defined(IMX214_MIPI_RAW)
    {IMX214_SENSOR_ID, SENSOR_DRVNAME_IMX214_MIPI_RAW, IMX214_MIPI_RAW_SensorInit},
#endif
#if defined(IMX237_MIPI_RAW)
    {IMX237_SENSOR_ID, SENSOR_DRVNAME_IMX237_MIPI_RAW, IMX237_MIPI_RAW_SensorInit},
#endif
#if defined(IMX190_MIPI_RAW)
    {IMX190_SENSOR_ID, SENSOR_DRVNAME_IMX190_MIPI_RAW, IMX190_MIPI_RAW_SensorInit},
#endif
#if defined(IMX149_MIPI_RAW)
    {IMX149_SENSOR_ID, SENSOR_DRVNAME_IMX149_MIPI_RAW, IMX149_MIPI_RAW_SensorInit},
#endif
#if defined(IMX258_MIPI_RAW)
	{IMX258_SENSOR_ID, SENSOR_DRVNAME_IMX258_MIPI_RAW, IMX258_MIPI_RAW_SensorInit},
#endif
/* S5K */
#if defined(S5K3H7_MIPI_RAW)
    {S5K3H7_SENSOR_ID, SENSOR_DRVNAME_S5K3H7_MIPI_RAW, S5K3H7_MIPI_RAW_SensorInit},
#endif
/* GC */
#if defined(GC5025_MIPI_RAW)
    {GC5025_SENSOR_ID, SENSOR_DRVNAME_GC5025_MIPI_RAW,GC5025_MIPI_RAW_SensorInit},
#endif
#if defined(GC2755_MIPI_RAW)
    {GC2755_SENSOR_ID, SENSOR_DRVNAME_GC2755_MIPI_RAW,GC2755_MIPI_RAW_SensorInit},
#endif
#if defined(GC2755_1LANE_MIPI_RAW)
    {GC2755_1LANE_SENSOR_ID, SENSOR_DRVNAME_GC2755_1LANE_MIPI_RAW,GC2755_1LANE_MIPI_RAW_SensorInit},
#endif
#if defined(GC2365_MIPI_RAW)
    {GC2365MIPI_SENSOR_ID,SENSOR_DRVNAME_GC2365MIPI_RAW,GC2365MIPI_RAW_SensorInit},
#endif
#if defined(GC2355_MIPI_RAW)
	{GC2355_SENSOR_ID,SENSOR_DRVNAME_GC2355_MIPI_RAW,GC2355_MIPI_RAW_SensorInit},
#endif
#if defined(GC2375_MIPI_RAW)
    {GC2375MIPI_SENSOR_ID,SENSOR_DRVNAME_GC2375MIPI_RAW,GC2375MIPI_RAW_SensorInit},
#endif
#if defined(GC5005_MIPI_RAW)
    {GC5005MIPI_SENSOR_ID, SENSOR_DRVNAME_GC5005MIPI_RAW,GC5005MIPI_RAW_SensorInit},
#endif
#if defined(GC5005_SUB_MIPI_RAW)
    {GC5005MIPI_SUB_SENSOR_ID, SENSOR_DRVNAME_GC5005MIPI_SUB_RAW,GC5005MIPI_SUB_RAW_SensorInit},
#endif
#if defined(GC8024_MIPI_RAW)
    {GC8024MIPI_SENSOR_ID, SENSOR_DRVNAME_GC8024MIPI_RAW,GC8024MIPI_RAW_SensorInit},
#endif
#if defined(GC2385_MIPI_RAW)
    {GC2385MIPI_SENSOR_ID, SENSOR_DRVNAME_GC2385MIPI_RAW, GC2385MIPI_RAW_SensorInit},
#endif
#if defined(GC2155MIPI_YUV)
    {GC2155MIPI_SENSOR_ID, SENSOR_DRVNAME_GC2155MIPI_RAW_YUV, GC2155MIPI_YUV_SensorInit},
#endif
#if defined(GC8034_MIPI_RAW)
    {GC8034MIPI_SENSOR_ID, SENSOR_DRVNAME_GC8034MIPI_RAW,GC8034MIPI_RAW_SensorInit},
#endif
#if defined(GC0310_MIPI_YUV)
    {GC0310_SENSOR_ID, SENSOR_DRVNAME_GC0310_MIPI_YUV,GC0310_YUV_SensorInit},
#endif

/* SP */
#if defined(SP2509_MIPI_RAW)
    {SP2509MIPI_SENSOR_ID,SENSOR_DRVNAME_SP2509_MIPI_RAW,SP2509MIPISensorInit},
#endif
#if defined(SP250A_MIPI_RAW)
    {SP250AMIPI_SENSOR_ID,SENSOR_DRVNAME_SP250A_MIPI_RAW,SP250A_MIPI_RAW_SensorInit},
#endif
#if defined(SP2609_MIPI_RAW)
	{SP2609MIPI_SENSOR_ID,SENSOR_DRVNAME_SP2609_MIPI_RAW,SP2609MIPISensorInit},
#endif
#if defined(SP8407_MIPI_RAW)
    {SP8407MIPI_SENSOR_ID,SENSOR_DRVNAME_SP8407_MIPI_RAW,SP8407_MIPI_RAW_SensorInit},
#endif
#if defined(SP5506_MIPI_RAW)
    {SP5506MIPI_SENSOR_ID,SENSOR_DRVNAME_SP5506_MIPI_RAW,SP5506MIPISensorInit},
#endif
#if defined(SP5506_SUB_MIPI_RAW)
    {SP5506_SUB_MIPI_SENSOR_ID,SENSOR_DRVNAME_SP5506_SUB_MIPI_RAW,SP5506_SUB_MIPISensorInit},
#endif
#if defined(SP5407_MIPI_RAW)
    {SP5407MIPI_SENSOR_ID,SENSOR_DRVNAME_SP5407_MIPI_RAW,SP5407_MIPI_RAW_SensorInit},
#endif
#if defined(SP5509_MIPI_RAW)
    {SP5509MIPI_SENSOR_ID,SENSOR_DRVNAME_SP5509_MIPI_RAW,SP5509MIPI_RAW_SensorInit},
#endif
/* MN */
#if defined(MN34172_MIPI_RAW)
    {MN34172_SENSOR_ID, SENSOR_DRVNAME_MN34172_MIPI_RAW,MN34172_MIPI_RAW_SensorInit},
#endif
#if defined(MN045_MIPI_RAW)
    {MN045_SENSOR_ID,SENSOR_DRVNAME_MN045_MIPI_RAW,MN045MIPISensorInit},
#endif
/* S5K */
#if defined(S5K3L2_MIPI_RAW)
    {S5K3L2_SENSOR_ID, SENSOR_DRVNAME_S5K3L2_MIPI_RAW, S5K3L2_MIPI_RAW_SensorInit},
#endif

#if defined(S5K3M2_MIPI_RAW)
    {S5K3M2_SENSOR_ID, SENSOR_DRVNAME_S5K3M2_MIPI_RAW, S5K3M2_MIPI_RAW_SensorInit},
#endif

#if defined(S5K3L8_MIPI_RAW)
    {S5K3L8_SENSOR_ID, SENSOR_DRVNAME_S5K3L8_MIPI_RAW, S5K3L8_MIPI_RAW_SensorInit},
#endif

#if defined(S5K4H8_MIPI_RAW)
    {S5K4H8_SENSOR_ID,SENSOR_DRVNAME_S5K4H8_MIPI_RAW,S5K4H8_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3H7YX_MIPI_RAW)
    {S5K3H7YX_SENSOR_ID, SENSOR_DRVNAME_S5K3H7YX_MIPI_RAW, S5K3H7YX_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3H2_MIPI_RAW)
    {S5K3H2_SENSOR_ID, SENSOR_DRVNAME_S5K3H2_MIPI_RAW, S5K3H2_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3H2_MIPI_RAW_CXT)
    {S5K3H2_SENSOR_ID_CXT, SENSOR_DRVNAME_S5K3H2_MIPI_RAW_CXT, S5K3H2_MIPI_RAW_CXT_SensorInit},
#endif
/*HI*/
#if defined(HI545_MIPI_RAW)
	{HI545MIPI_SENSOR_ID, SENSOR_DRVNAME_HI545_MIPI_RAW, HI545_MIPI_RAW_SensorInit},
#endif
#if defined(HI351_MIPI_YUV)
{HI351MIPI_SENSOR_ID,SENSOR_DRVNAME_HI351_MIPI_YUV,HI351_YUV_SensorInit},
#endif

/*AR*/
#if defined(AR0543_MIPI_RAW)
    {AR0543MIPI_SENSOR_ID, SENSOR_DRVNAME_AR0543_MIPI_RAW, AR0543_MIPI_RAW_SensorInit},
#endif

/* IMX */
#if defined(IMX219_MIPI_RAW)
    {IMX219_SENSOR_ID, SENSOR_DRVNAME_IMX219_MIPI_RAW, IMX219_MIPI_RAW_SensorInit},
#endif

/*  ADD sensor driver before this line */
    {0,{0},NULL}, //end of list
};
//e_add new sensor driver here

