
# Linux driver folder
# Vanzo:yucheng on: Sun, 24 Jan 2016 18:13:26 +0800
# Modified for vanzo customization
# include $(srctree)/drivers/misc/mediatek/Makefile.custom
# End of Vanzo: yucheng

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/lu2x3x/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/

obj-y	+=  leadingui_lu2x3x.o
