#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
#Droi.xushuai,20161024,add fingerprint sunwave
obj-$(CONFIG_MTK_SUNWAVECORP) += sunwavecorp/
obj-$(CONFIG_MTK_SUNWAVECORP_TEE) += sunwavecorp_tee/
obj-$(CONFIG_FINGERPRINT_MA120N) += ma120n/
obj-$(CONFIG_FINGERPRINT_MA120N_TEE) += ma120n_tee/
obj-$(CONFIG_MA083T_FINGERPRINT) += ma083t/
obj-$(CONFIG_MA080T_FINGERPRINT) += ma080t/
obj-$(CONFIG_FINGERPRINT_GF3258) += gf3258/
obj-$(CONFIG_FINGERPRINT_MA096N) += ma096n/
obj-$(CONFIG_MTK_MA116N) += ma116n/
obj-$(CONFIG_MTK_MA118N_TEE) += ma118n_tee/
obj-$(CONFIG_MA083T_TEE_FINGERPRINT) += ma083t_tee/
